# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: us-states.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fus-states.proto\x12\tus_states\"-\n\nStateProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpost_abbr\x18\x02 \x01(\tb\x06proto3')



_STATEPROTO = DESCRIPTOR.message_types_by_name['StateProto']
StateProto = _reflection.GeneratedProtocolMessageType('StateProto', (_message.Message,), {
  'DESCRIPTOR' : _STATEPROTO,
  '__module__' : 'us_states_pb2'
  # @@protoc_insertion_point(class_scope:us_states.StateProto)
  })
_sym_db.RegisterMessage(StateProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATEPROTO._serialized_start=30
  _STATEPROTO._serialized_end=75
# @@protoc_insertion_point(module_scope)
