# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inventory_event.proto\"\x8a\x01\n\x0eInventoryEvent\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\x17\n\x0fquantity_change\x18\x03 \x01(\x05\x12\x15\n\rcurrent_stock\x18\x04 \x01(\x05\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x12\n\nevent_time\x18\x06 \x01(\tb\x06proto3')



_INVENTORYEVENT = DESCRIPTOR.message_types_by_name['InventoryEvent']
InventoryEvent = _reflection.GeneratedProtocolMessageType('InventoryEvent', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYEVENT,
  '__module__' : 'inventory_event_pb2'
  # @@protoc_insertion_point(class_scope:InventoryEvent)
  })
_sym_db.RegisterMessage(InventoryEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORYEVENT._serialized_start=26
  _INVENTORYEVENT._serialized_end=164
# @@protoc_insertion_point(module_scope)
